# Generated by Django 3.2.7 on 2022-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='login time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('todo', models.CharField(max_length=255, verbose_name='do')),
                ('priority', models.IntegerField(choices=[(0, 'small'), (1, 'mid'), (2, 'large')], verbose_name='priority')),
                ('complete_flag', models.BooleanField(default=False, verbose_name='flag')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'task',
                'db_table': 'task',
            },
        ),
    ]
